"""Fusion related helpers for collocation derived diagnostics."""

from __future__ import annotations

import numpy as np
import xarray as xr


def _find_first_variable(ds: xr.Dataset, names: list[str]) -> xr.DataArray | None:
    """Return the first variable in *ds* that matches one of ``names``."""

    for name in names:
        if name in ds:
            return ds[name]
    return None


def estimate_bias_from_collocation(tc: xr.Dataset) -> xr.DataArray:
    """Return bias estimates inferred from a collocation dataset.

    Parameters
    ----------
    tc:
        Dataset generated by TC/IVD/EIVD style routines.

    Returns
    -------
    :class:`xarray.DataArray`
        Bias per model.  When the dataset does not contain explicit bias
        estimates, a zero bias aligned with the variance diagnostics is
        returned.  This mirrors the inverse variance weighting fallback.
    """

    if not isinstance(tc, xr.Dataset):
        raise TypeError("'tc' must be an xarray.Dataset instance")

    bias_da = _find_first_variable(
        tc,
        [
            "bias",
            "bias_mean",
            "bias_estimate",
            "mean_bias",
            "biases",
        ],
    )

    if bias_da is not None:
        if bias_da.ndim != 1:
            raise ValueError("Bias array must be one-dimensional")
        return bias_da.astype(float).rename("bias")

    var_da = _find_first_variable(tc, ["var", "variance", "var_diag", "sigma2", "error_var"])
    if var_da is not None and var_da.ndim == 1:
        zeros = np.zeros_like(var_da.astype(float).values)
        return xr.DataArray(zeros, coords=var_da.coords, dims=var_da.dims, name="bias")

    return xr.DataArray(np.array(0.0), dims=(), name="bias")

